// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWc9weIhddANvKHd30qdqKhf1nnUri5o',
    appId: '1:988081859935:web:954c60aae96945381e9aea',
    messagingSenderId: '988081859935',
    projectId: 'aidx-b75e7',
    authDomain: 'aidx-b75e7.firebaseapp.com',
    storageBucket: 'aidx-b75e7.firebasestorage.app',
    measurementId: 'G-KQJY2WGNJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_h0UHIFE65u7YsFhxXDO1MFDKwjheeY',
    appId: '1:988081859935:android:518aaa6466be57a91e9aea',
    messagingSenderId: '988081859935',
    projectId: 'aidx-b75e7',
    storageBucket: 'aidx-b75e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzM13JASlSpAQf3P5eQId78W1AwsUIlo',
    appId: '1:1057037815712:ios:1e0b23409b9567bf255ec5',
    messagingSenderId: '1057037815712',
    projectId: 'medigay-65f83',
    storageBucket: 'medigay-65f83.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzM13JASlSpAQf3P5eQId78W1AwsUIlo',
    appId: '1:1057037815712:macos:1e0b23409b9567bf255ec5',
    messagingSenderId: '1057037815712',
    projectId: 'medigay-65f83',
    storageBucket: 'medigay-65f83.appspot.com',
  );
} 